Replace postinstall with prepublishOnly
bitfinexcom/bfx-hf-indicators pull request #66
Opened 2021-04-20 17:19 UTC by vitaliystoliarovcc

### Description:

Asana ticket: https://app.asana.com/0/1125859137800433/1200174906704565/f

2021-04-21 06:08 UTC, avsek477 requested changes
we should move the babel packages from dependencies to devDependencies as well ?

2021-04-21 07:31 UTC, robertkowalski commented
when you test a publish, is the `dist` folder included in the package tarball?

2021-04-21 09:51 UTC, vitaliystoliarovcc commented
> when you test a publish, is the dist folder included in the package tarball? 

No, the same issue is present on https://www.jsdelivr.com/package/npm/bfx-hf-indicators?version=2.0.5
Seems like 'postinstall' fixes it on install stage

Regarding this PR, a lot will depend on how you execute `npm publish` command.

2021-04-21 09:59 UTC, vitaliystoliarovcc commented
In fact, the prepublishOnly` script is not the only change required.

At the moment I see the following problems:
1. `build` script copies package.json, but it is not used for publication (because of step 2)
2. The root folder with the source code is published in npmjs (since package.json is copied to dist, we can only publish the content from this folder, which is common practice since we don't need test directories or any configuration files for distribution)

What do you think?

2021-04-21 10:19 UTC, robertkowalski commented
- i like both solutions and both work well
 - for #2 i like that the source is still available in the local npm modules, which can make local debugging a bit easier

2021-04-21 11:48 UTC, robertkowalski commented on .gitignore
> +*.tgz
missing newline at end of file

you can enable it as an editor setting

2021-04-21 11:48 UTC, robertkowalski commented on .npmignore
> +.babelrc
same here

2021-04-21 11:50 UTC, robertkowalski requested changes
looks nice, two small nits with EOF newlines

2021-04-22 11:19 UTC, robertkowalski approved these changes
lgtm

2021-04-22 11:19 UTC, merged